default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-added-large-files
            args:
                - '--maxkb=10000'
          - id: end-of-file-fixer
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.16.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional']
            stages:
                - commit-msg
    - repo: https://github.com/prettier/pre-commit
      rev: v2.1.2
      hooks:
          - id: prettier

    - repo: local
      hooks:
          - id: eslint
            name: eslint
            entry: npx -y eslint
            pass_filenames: true
            language: system
            files: \.(ts|html)$
