default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-added-large-files
            args:
                - '--maxkb=10000'
          - id: end-of-file-fixer
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.16.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional']
            stages:
                - commit-msg
    - repo: https://github.com/prettier/pre-commit
      rev: v2.1.2
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.6.0'
      hooks:
          - id: eslint
            args:
                - '--fix'
                - '--config'
                - 'eslint.config.js'
            additional_dependencies:
                - eslint@9.6.0
                - '@eslint/js@9.6.0'
                - 'typescript-eslint@7.15.0'
                - 'angular-eslint@18.1.0'
                - eslint-config-prettier@9.1.0
            files: \.(ts|html)$
            types: [file]
