name: Create and publish a Docker image

on:
    workflow_run:
        workflows:
            - Linting
        types:
            - completed
        branches:
            - main
    push:
        tags:
            - '**'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: accenture/federated-catalogue-viewer
    IMAGE_TAG: ''
jobs:
    generate-next-release-version:
        if: ${{ github.ref_type == 'branch' }}
        uses: ./.github/workflows/semantic-release.yaml
        with:
            dry-run: true

    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Determine Image Tag
              if: ${{ github.ref_type == 'branch' }}
              run: |
                  echo \"IMAGE_TAG=${{env.NEXT_RELEASE_VERSION}}-pre-release-$(git rev-parse --short ${{ github.sha }})\" >> $GITHUB_ENV
            - name: Determine Image Tag
              if: ${{ github.ref_type == 'tag' }}
              run: |
                  echo \"IMAGE_TAG=${{github.ref_name}}\" >> $GITHUB_ENV

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  context: .
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
